### ISSUE TITLE
hubot bm set api key <key_id>:<key_secret> not working

### ISSUE THREAD

**Issue by SanjuTechie87** [Blazemeter/hubot-blazemeter#2]
Hi Gilad, Thanks for acknowledging and updating the code. I am trying with the new updated source code, but I am not seeing the option to set bm set api key api id: secret key option when using the command Hubot help. 

myhubot bm get api key
myhubot bm get env
myhubot bm list (tests|collections|masters|sessions)
myhubot bm list running (tests|collections|masters|sessions)
myhubot bm run test <test_id>
myhubot bm set api key <apiKey>
myhubot bm set env <env>
myhubot bm stop test <test_id>
myhubot bm whoami

Note: I tried with providing my Blazemeter api key id: secret id but nothing is happening. Though the error has now changed. I am getting 401 unauthorised now .

Could you please look into it. Thanks in advance

**Comment by pgilad** [comment]
Yep, I see the error, will fix in a minute

**Comment by pgilad** [comment]
Fixed in https://github.com/Blazemeter/hubot-blazemeter/releases/tag/v2.1.0 please try again 🙏

**Comment by SanjuTechie87** [comment]
Hi Gilad, Again thanks much for the fix . Now I am able to login . In response to hubot bm whoami command I am getting back Shell: Successfully checked in with https://a.blazemeter.com. But now the issue is no other commands are working like :

hubot bm list (tests|collections|masters|sessions)
hubot bm list running (tests|collections|masters|sessions)
hubot bm run test <test_id>

The first two commands returning nothing. hubot bm run test <test_id> - this one returning  the below:

Shell: Launching test 6940042. This might take a while...
Shell: Got 404: Not Found 

whereas I have one test in Blazemeter with id 6940042. Again require your kind help. Thanks a lot.

**Comment by pgilad** [comment]
What happens when you run:
`hubot bm whoami` ?

Oh nevermind, I see that it works well. Let me check it..
